---
title: "Airbnb EDA"
author: "Ziyu Jin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
  # pdf_document: 
  #   latex_engine: xelatex
---

```{r setup, include=FALSE}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 

# Clear environment of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE) {
  lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), 
         detach, character.only = TRUE, unload = TRUE)
}
```

```{r}
#install.packages("dplyr")
library(dplyr)
library(DataCombine)
```


```{r}
df <- read.csv("airbnb.csv")
#df <- filter(df, successful_booking == "yes")
df <- filter(df, !channel == "instant_book")
#
```

```{r}

df$channel = factor(df$channel, levels = c('contact_me', 'book_it'))
levels(df$channel)
```

```{r}
df$interactions  = factor(df$interactions, levels=c('<=3','3-5','5-8','8-10','10-15','15-20','20-25','25-30','>30'))
df$reviews  = factor(df$reviews, levels=c('<=5','5-10','10-15','15-20','20-30','30-50','50-100','100-200', '>200'))
df$lead_time_in_weeks  = factor(df$lead_time_in_weeks, levels=c('<=1d','1-3d','3d-1w','1-2w','2-3w','3-4w','4-5w','5-6w','6-7w','7-8w','8-10w','10-12w','3-4m','4-5m','5-6m','6-7m','7-8m','>8m'))
df$duration_of_stay  = factor(df$duration_of_stay, levels=c('1d','1-3d','3-5d','5-7d','7-10d','10-15d','15-20d','20-30d','>30d'))
#df$words_guest  = factor(df$words_guest, levels=c('<=1','1-10','10-20','20-50','50-100','100-200','>200'))
df$words_host  = factor(df$words_host, levels=c('<=1','1-10','10-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100','100-120','120-140','140-160','160-180','180-200','200-220','220-250','>250'))
df$message_length_in_char  = factor(df$message_length_in_char, levels=c('<=1','1-20','20-50','50-100','100-150','150-200','200-250','250-300','300-400','400-500','>500'))
df$reply_t_in_m  = factor(df$reply_t_in_m, levels=c('<=1m','1-10m','10-30m','30m-1h','1h-3h','3-6h','6-12h','12-24h','1-2d','>2d'))
df$accept_t_in_m  = factor(df$accept_t_in_m, levels=c('<=1m','1-10m','10-30m','30m-1h','1h-3h','3-6h','6-12h','12-24h','1-2d','>2d'))
df$guest_size_bin  = factor(df$guest_size_bin, levels=c('<=1','1-2','2-4','4-6','6-8','8-10','>10'))
#df$channel  = factor(df$channel, levels=c('contact_me','book_it','instant_book'))
#df$room_type  = factor(df$channel, levels=c('Shared room','Private room','Entire home/apt'))
#df <- DropNA(df, Var="room_type", message = TRUE)

```


```{r}
# interactions
mosaicplot(~ interactions + channel + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ interactions + message_length_in_char + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ interactions + reply_t_in_m + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ interactions + duration_of_stay + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ interactions + lead_time_in_weeks + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ interactions + reviews + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
```


```{r}
# user stage
mosaicplot(~ user_stage + message_length_in_char + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ user_stage + duration_of_stay + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ user_stage + channel + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ user_stage + reviews + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
```

```{r}
# channel 
mosaicplot(~ channel + duration_of_stay + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ channel + reviews + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ channel + guest_size_bin + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
```


```{r}
# stay
mosaicplot(~ duration_of_stay + message_length_in_char + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
mosaicplot(~ duration_of_stay + room_type + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
```

```{r}
# message
mosaicplot(~ message_length_in_char + guest_size_bin + successful_booking, data = df, cex.axis = 0.85, color = TRUE)
```






























